// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/quintilesims/layer0/api/provider (interfaces: EnvironmentProvider)

package mock_provider

import (
	gomock "github.com/golang/mock/gomock"
	models "github.com/quintilesims/layer0/common/models"
)

// Mock of EnvironmentProvider interface
type MockEnvironmentProvider struct {
	ctrl     *gomock.Controller
	recorder *_MockEnvironmentProviderRecorder
}

// Recorder for MockEnvironmentProvider (not exported)
type _MockEnvironmentProviderRecorder struct {
	mock *MockEnvironmentProvider
}

func NewMockEnvironmentProvider(ctrl *gomock.Controller) *MockEnvironmentProvider {
	mock := &MockEnvironmentProvider{ctrl: ctrl}
	mock.recorder = &_MockEnvironmentProviderRecorder{mock}
	return mock
}

func (_m *MockEnvironmentProvider) EXPECT() *_MockEnvironmentProviderRecorder {
	return _m.recorder
}

func (_m *MockEnvironmentProvider) Create(_param0 models.CreateEnvironmentRequest) (string, error) {
	ret := _m.ctrl.Call(_m, "Create", _param0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockEnvironmentProviderRecorder) Create(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Create", arg0)
}

func (_m *MockEnvironmentProvider) Delete(_param0 string) error {
	ret := _m.ctrl.Call(_m, "Delete", _param0)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockEnvironmentProviderRecorder) Delete(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Delete", arg0)
}

func (_m *MockEnvironmentProvider) List() ([]models.EnvironmentSummary, error) {
	ret := _m.ctrl.Call(_m, "List")
	ret0, _ := ret[0].([]models.EnvironmentSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockEnvironmentProviderRecorder) List() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "List")
}

func (_m *MockEnvironmentProvider) Read(_param0 string) (*models.Environment, error) {
	ret := _m.ctrl.Call(_m, "Read", _param0)
	ret0, _ := ret[0].(*models.Environment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockEnvironmentProviderRecorder) Read(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Read", arg0)
}

func (_m *MockEnvironmentProvider) Update(_param0 string, _param1 models.UpdateEnvironmentRequest) error {
	ret := _m.ctrl.Call(_m, "Update", _param0, _param1)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockEnvironmentProviderRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Update", arg0, arg1)
}
