// Generated by go-decorator, DO NOT EDIT
package autoscaling

type ProviderDecorator struct {
	Inner     Provider
	Decorator func(name string, call func() error) error
}

func (this *ProviderDecorator) AttachLoadBalancer(p0 string, p1 string) (err error) {
	call := func() error {
		var err error
		err = this.Inner.AttachLoadBalancer(p0, p1)
		return err
	}
	err = this.Decorator("AttachLoadBalancer", call)
	return err
}
func (this *ProviderDecorator) CreateLaunchConfiguration(p0 *string, p1 *string, p2 *string, p3 *string, p4 *string, p5 *string, p6 []*string) (err error) {
	call := func() error {
		var err error
		err = this.Inner.CreateLaunchConfiguration(p0, p1, p2, p3, p4, p5, p6)
		return err
	}
	err = this.Decorator("CreateLaunchConfiguration", call)
	return err
}
func (this *ProviderDecorator) CreateAutoScalingGroup(p0 string, p1 string, p2 string, p3 int, p4 int) (err error) {
	call := func() error {
		var err error
		err = this.Inner.CreateAutoScalingGroup(p0, p1, p2, p3, p4)
		return err
	}
	err = this.Decorator("CreateAutoScalingGroup", call)
	return err
}
func (this *ProviderDecorator) SetDesiredCapacity(p0 string, p1 int) (err error) {
	call := func() error {
		var err error
		err = this.Inner.SetDesiredCapacity(p0, p1)
		return err
	}
	err = this.Decorator("SetDesiredCapacity", call)
	return err
}
func (this *ProviderDecorator) UpdateAutoScalingGroupMaxSize(p0 string, p1 int) (err error) {
	call := func() error {
		var err error
		err = this.Inner.UpdateAutoScalingGroupMaxSize(p0, p1)
		return err
	}
	err = this.Decorator("UpdateAutoScalingGroupMaxSize", call)
	return err
}
func (this *ProviderDecorator) UpdateAutoScalingGroupMinSize(p0 string, p1 int) (err error) {
	call := func() error {
		var err error
		err = this.Inner.UpdateAutoScalingGroupMinSize(p0, p1)
		return err
	}
	err = this.Decorator("UpdateAutoScalingGroupMinSize", call)
	return err
}
func (this *ProviderDecorator) DescribeAutoScalingGroups(p0 []*string) (v0 []*Group, err error) {
	call := func() error {
		var err error
		v0, err = this.Inner.DescribeAutoScalingGroups(p0)
		return err
	}
	err = this.Decorator("DescribeAutoScalingGroups", call)
	return v0, err
}
func (this *ProviderDecorator) DescribeAutoScalingGroup(p0 string) (v0 *Group, err error) {
	call := func() error {
		var err error
		v0, err = this.Inner.DescribeAutoScalingGroup(p0)
		return err
	}
	err = this.Decorator("DescribeAutoScalingGroup", call)
	return v0, err
}
func (this *ProviderDecorator) DescribeLaunchConfigurations(p0 []*string) (v0 []*LaunchConfiguration, err error) {
	call := func() error {
		var err error
		v0, err = this.Inner.DescribeLaunchConfigurations(p0)
		return err
	}
	err = this.Decorator("DescribeLaunchConfigurations", call)
	return v0, err
}
func (this *ProviderDecorator) DescribeLaunchConfiguration(p0 string) (v0 *LaunchConfiguration, err error) {
	call := func() error {
		var err error
		v0, err = this.Inner.DescribeLaunchConfiguration(p0)
		return err
	}
	err = this.Decorator("DescribeLaunchConfiguration", call)
	return v0, err
}
func (this *ProviderDecorator) DeleteAutoScalingGroup(p0 *string) (err error) {
	call := func() error {
		var err error
		err = this.Inner.DeleteAutoScalingGroup(p0)
		return err
	}
	err = this.Decorator("DeleteAutoScalingGroup", call)
	return err
}
func (this *ProviderDecorator) DeleteLaunchConfiguration(p0 *string) (err error) {
	call := func() error {
		var err error
		err = this.Inner.DeleteLaunchConfiguration(p0)
		return err
	}
	err = this.Decorator("DeleteLaunchConfiguration", call)
	return err
}
func (this *ProviderDecorator) TerminateInstanceInAutoScalingGroup(p0 string, p1 bool) (v0 *Activity, err error) {
	call := func() error {
		var err error
		v0, err = this.Inner.TerminateInstanceInAutoScalingGroup(p0, p1)
		return err
	}
	err = this.Decorator("TerminateInstanceInAutoScalingGroup", call)
	return v0, err
}
