FROM golang:1.6.2

ENV APP gitlab.imshealth.com/xfra/layer0
RUN mkdir -p /go/src/$APP
WORKDIR /go/src/$APP
ENTRYPOINT [ "/bin/sh", "-c" ]

COPY . /go/src/$APP/

WORKDIR /go/src/$APP/api

RUN make deps
RUN make build-cgo

WORKDIR /go/src/$APP
CMD ["./api"]
