# Project information
site_name: Layer0
site_description: Layer0 Documentation
site_author: xfra
site_url: https://github.com/quintilesims/layer0/
extra_css: ['stylesheets/extra.css']

# Repository
repo_name: GitHub
repo_url: https://github.com/quintilesims/layer0/

pages:
  - Home: index.md
  - Releases: releases.md
  - Introduction: intro.md
  - Setup:
    - Install: setup/install.md
    - Upgrade: setup/upgrade.md
    - Destroy: setup/destroy.md
  - Guides:
    - "Walkthrough: Introduction": guides/walkthrough/intro.md
    - "Walkthrough: Deployment 1": guides/walkthrough/deployment-1.md
    - "Walkthrough: Deployment 2": guides/walkthrough/deployment-2.md
    - "Walkthrough: Deployment 3": guides/walkthrough/deployment-3.md
    - Terraform beyond Layer0: guides/terraform_beyond_layer0.md
    - One-off Task: guides/one_off_task.md
  - Reference:
    - Layer0 CLI: reference/cli.md
    - Layer0 Setup CLI: reference/setup-cli.md
    - Terraform: reference/terraform_introduction.md
    - Layer0 Terraform Plugin: reference/terraform-plugin.md
    - Updating a Service: reference/updateservice.md
    - Consul: reference/consul.md
    - Task Definitions: reference/task_definition.md
    - Architecture: reference/architecture.md
    - ECR: reference/ecr.md
  - Troubleshooting:
    - Common Issues: troubleshooting/commonissues.md
    - Secure Shell (SSH): troubleshooting/ssh.md

site_dir: ../docs

theme:
    name: 'material'
    custom_dir: 'material'
    palette:
        primary: 'red'
        accent:  'grey'
    font:
        text: 'Roboto'
        code: 'Roboto Mono'
    logo: 'static/logo_icon.png'

markdown_extensions:
  - codehilite
  - admonition
  - toc:
      permalink: '#'
