// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/quintilesims/layer0/api/scheduler/resource (interfaces: ConsumerGetter)

package mock_resource

import (
	gomock "github.com/golang/mock/gomock"
	resource "github.com/quintilesims/layer0/api/scheduler/resource"
)

// Mock of ConsumerGetter interface
type MockConsumerGetter struct {
	ctrl     *gomock.Controller
	recorder *_MockConsumerGetterRecorder
}

// Recorder for MockConsumerGetter (not exported)
type _MockConsumerGetterRecorder struct {
	mock *MockConsumerGetter
}

func NewMockConsumerGetter(ctrl *gomock.Controller) *MockConsumerGetter {
	mock := &MockConsumerGetter{ctrl: ctrl}
	mock.recorder = &_MockConsumerGetterRecorder{mock}
	return mock
}

func (_m *MockConsumerGetter) EXPECT() *_MockConsumerGetterRecorder {
	return _m.recorder
}

func (_m *MockConsumerGetter) GetConsumers(_param0 string) ([]resource.ResourceConsumer, error) {
	ret := _m.ctrl.Call(_m, "GetConsumers", _param0)
	ret0, _ := ret[0].([]resource.ResourceConsumer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockConsumerGetterRecorder) GetConsumers(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetConsumers", arg0)
}
