// Automatically generated by MockGen. DO NOT EDIT!
// Source: gitlab.imshealth.com/xfra/layer0/cli/command (interfaces: Resolver)

package mock_command

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of Resolver interface
type MockResolver struct {
	ctrl     *gomock.Controller
	recorder *_MockResolverRecorder
}

// Recorder for MockResolver (not exported)
type _MockResolverRecorder struct {
	mock *MockResolver
}

func NewMockResolver(ctrl *gomock.Controller) *MockResolver {
	mock := &MockResolver{ctrl: ctrl}
	mock.recorder = &_MockResolverRecorder{mock}
	return mock
}

func (_m *MockResolver) EXPECT() *_MockResolverRecorder {
	return _m.recorder
}

func (_m *MockResolver) Resolve(_param0 string, _param1 string) ([]string, error) {
	ret := _m.ctrl.Call(_m, "Resolve", _param0, _param1)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockResolverRecorder) Resolve(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Resolve", arg0, arg1)
}
