// Automatically generated by MockGen. DO NOT EDIT!
// Source: gitlab.imshealth.com/xfra/layer0/api/data (interfaces: JobData)

package mock_data

import (
	gomock "github.com/golang/mock/gomock"
	models "gitlab.imshealth.com/xfra/layer0/common/models"
	types "gitlab.imshealth.com/xfra/layer0/common/types"
)

// Mock of JobData interface
type MockJobData struct {
	ctrl     *gomock.Controller
	recorder *_MockJobDataRecorder
}

// Recorder for MockJobData (not exported)
type _MockJobDataRecorder struct {
	mock *MockJobData
}

func NewMockJobData(ctrl *gomock.Controller) *MockJobData {
	mock := &MockJobData{ctrl: ctrl}
	mock.recorder = &_MockJobDataRecorder{mock}
	return mock
}

func (_m *MockJobData) EXPECT() *_MockJobDataRecorder {
	return _m.recorder
}

func (_m *MockJobData) CreateJob(_param0 *models.Job) error {
	ret := _m.ctrl.Call(_m, "CreateJob", _param0)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockJobDataRecorder) CreateJob(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "CreateJob", arg0)
}

func (_m *MockJobData) DeleteJob(_param0 string) error {
	ret := _m.ctrl.Call(_m, "DeleteJob", _param0)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockJobDataRecorder) DeleteJob(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DeleteJob", arg0)
}

func (_m *MockJobData) GetJob(_param0 string) (*models.Job, error) {
	ret := _m.ctrl.Call(_m, "GetJob", _param0)
	ret0, _ := ret[0].(*models.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockJobDataRecorder) GetJob(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetJob", arg0)
}

func (_m *MockJobData) GetMeta(_param0 string) (map[string]string, error) {
	ret := _m.ctrl.Call(_m, "GetMeta", _param0)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockJobDataRecorder) GetMeta(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetMeta", arg0)
}

func (_m *MockJobData) ListJobs() ([]*models.Job, error) {
	ret := _m.ctrl.Call(_m, "ListJobs")
	ret0, _ := ret[0].([]*models.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockJobDataRecorder) ListJobs() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ListJobs")
}

func (_m *MockJobData) SetMeta(_param0 string, _param1 string, _param2 string) error {
	ret := _m.ctrl.Call(_m, "SetMeta", _param0, _param1, _param2)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockJobDataRecorder) SetMeta(arg0, arg1, arg2 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SetMeta", arg0, arg1, arg2)
}

func (_m *MockJobData) UpdateJobStatus(_param0 string, _param1 types.JobStatus) error {
	ret := _m.ctrl.Call(_m, "UpdateJobStatus", _param0, _param1)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockJobDataRecorder) UpdateJobStatus(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "UpdateJobStatus", arg0, arg1)
}
