// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/quintilesims/layer0/api/scheduler (interfaces: JobScheduler)

package mock_scheduler

import (
	gomock "github.com/golang/mock/gomock"
	models "github.com/quintilesims/layer0/common/models"
)

// Mock of JobScheduler interface
type MockJobScheduler struct {
	ctrl     *gomock.Controller
	recorder *_MockJobSchedulerRecorder
}

// Recorder for MockJobScheduler (not exported)
type _MockJobSchedulerRecorder struct {
	mock *MockJobScheduler
}

func NewMockJobScheduler(ctrl *gomock.Controller) *MockJobScheduler {
	mock := &MockJobScheduler{ctrl: ctrl}
	mock.recorder = &_MockJobSchedulerRecorder{mock}
	return mock
}

func (_m *MockJobScheduler) EXPECT() *_MockJobSchedulerRecorder {
	return _m.recorder
}

func (_m *MockJobScheduler) ScheduleJob(_param0 models.CreateJobRequest) (string, error) {
	ret := _m.ctrl.Call(_m, "ScheduleJob", _param0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockJobSchedulerRecorder) ScheduleJob(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ScheduleJob", arg0)
}
