// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/quintilesims/layer0/api/entity (interfaces: Job)

package mock_entity

import (
	gomock "github.com/golang/mock/gomock"
	models "github.com/quintilesims/layer0/common/models"
)

// Mock of Job interface
type MockJob struct {
	ctrl     *gomock.Controller
	recorder *_MockJobRecorder
}

// Recorder for MockJob (not exported)
type _MockJobRecorder struct {
	mock *MockJob
}

func NewMockJob(ctrl *gomock.Controller) *MockJob {
	mock := &MockJob{ctrl: ctrl}
	mock.recorder = &_MockJobRecorder{mock}
	return mock
}

func (_m *MockJob) EXPECT() *_MockJobRecorder {
	return _m.recorder
}

func (_m *MockJob) Delete() error {
	ret := _m.ctrl.Call(_m, "Delete")
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockJobRecorder) Delete() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Delete")
}

func (_m *MockJob) Model() (*models.Job, error) {
	ret := _m.ctrl.Call(_m, "Model")
	ret0, _ := ret[0].(*models.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockJobRecorder) Model() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Model")
}
