deps:
	docker login -u $(DOCKERHUB_USERNAME) -p $(DOCKERHUB_PASSWORD)

api:
	./flow.sh api

runner:
	./flow.sh runner

push: deps api runner

delete:
	./flow.sh delete

.PHONY: deps api runner push delete
