deps:
	go get github.com/imshealth/go-decorator
	go install github.com/imshealth/go-decorator


all: autoscaling ec2 ecs elb cloudwatchlogs

ecs:
	go-decorator -type Provider ../common/aws/ecs/ecs.go > ../common/aws/ecs/ecs_provider_decorator.go

ec2:
	go-decorator -type Provider ../common/aws/ec2/ec2.go > ../common/aws/ec2/ec2_provider_decorator.go

elb:
	go-decorator -type Provider ../common/aws/elb/elb.go > ../common/aws/elb/elb_provider_decorator.go

autoscaling:
	go-decorator -type Provider ../common/aws/autoscaling/autoscaling.go > ../common/aws/autoscaling/autoscaling_provider_decorator.go

cloudwatchlogs:
	go-decorator -type Provider ../common/aws/cloudwatchlogs/cloudwatchlogs.go > ../common/aws/cloudwatchlogs/cloudwatchlogs_provider_decorator.go

.PHONY: all autoscaling ec2 ecs elb cloudwatchlogs
