deps:
	go get github.com/golang/mock/mockgen/model
	go install github.com/golang/mock/mockgen

all: api cli

api: logic db backend aws scheduler

cli: client command

logic:
	mockgen github.com/quintilesims/layer0/api/logic DeployLogic > ../api/logic/mock_logic/mock_deploy_logic.go &
	mockgen github.com/quintilesims/layer0/api/logic EnvironmentLogic > ../api/logic/mock_logic/mock_environment_logic.go &
	mockgen github.com/quintilesims/layer0/api/logic ServiceLogic > ../api/logic/mock_logic/mock_service_logic.go &
	mockgen github.com/quintilesims/layer0/api/logic TaskLogic > ../api/logic/mock_logic/mock_task_logic.go &
	mockgen github.com/quintilesims/layer0/api/logic LoadBalancerLogic > ../api/logic/mock_logic/mock_load_balancer_logic.go &
	mockgen github.com/quintilesims/layer0/api/logic JobLogic > ../api/logic/mock_logic/mock_job_logic.go &

db:
	mockgen github.com/quintilesims/layer0/common/db/job_store JobStore > ../common/db/job_store/mock_job_store/mock_job_store.go &

backend:
	mockgen github.com/quintilesims/layer0/api/backend Backend > ../api/backend/mock_backend/mock_backend.go &

scheduler:
	mockgen github.com/quintilesims/layer0/api/scheduler EnvironmentScaler > ../api/scheduler/mock_scheduler/mock_environment_scaler.go
	mockgen github.com/quintilesims/layer0/api/scheduler/resource ProviderManager > ../api/scheduler/resource/mock_resource/mock_provider_manager.go
	mockgen github.com/quintilesims/layer0/api/scheduler/resource ConsumerGetter > ../api/scheduler/resource/mock_resource/mock_consumer_getter.go

aws:
	mockgen github.com/quintilesims/layer0/common/aws/autoscaling Provider > ../common/aws/autoscaling/mock_autoscaling/mock_autoscaling.go &
	mockgen github.com/quintilesims/layer0/common/aws/ec2 Provider > ../common/aws/ec2/mock_ec2/mock_ec2.go &
	mockgen github.com/quintilesims/layer0/common/aws/ecs Provider > ../common/aws/ecs/mock_ecs/mock_ecs.go &
	mockgen github.com/quintilesims/layer0/common/aws/elb Provider > ../common/aws/elb/mock_elb/mock_elb.go &
	mockgen github.com/quintilesims/layer0/common/aws/iam Provider > ../common/aws/iam/mock_iam/mock_iam.go &
	mockgen github.com/quintilesims/layer0/common/aws/s3 Provider > ../common/aws/s3/mock_s3/mock_s3.go &
	mockgen github.com/quintilesims/layer0/common/aws/cloudwatchlogs Provider > ../common/aws/cloudwatchlogs/mock_cloudwatchlogs/mock_cloudwatchlogs.go &

client:
	mockgen github.com/quintilesims/layer0/cli/client Client > ../cli/client/mock_client/mock_client.go &

command:
	mockgen github.com/quintilesims/layer0/cli/command Resolver > ../cli/command/mock_command/mock_resolver.go &
